// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: sampleapp.proto

package sampleapplication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sampleapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sampleapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sampleapp_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_sampleapp_proto protoreflect.FileDescriptor

var file_sampleapp_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x32, 0xb7, 0x01, 0x0a, 0x11, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0c, 0x44, 0x6f, 0x55, 0x6e, 0x61, 0x72,
	0x79, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x0d,
	0x44, 0x6f, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x08, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x27, 0x0a, 0x0d, 0x44, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x2a,
	0x0a, 0x0e, 0x44, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sampleapp_proto_rawDescOnce sync.Once
	file_sampleapp_proto_rawDescData = file_sampleapp_proto_rawDesc
)

func file_sampleapp_proto_rawDescGZIP() []byte {
	file_sampleapp_proto_rawDescOnce.Do(func() {
		file_sampleapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_sampleapp_proto_rawDescData)
	})
	return file_sampleapp_proto_rawDescData
}

var file_sampleapp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sampleapp_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: Message
}
var file_sampleapp_proto_depIdxs = []int32{
	0, // 0: SampleApplication.DoUnaryUnary:input_type -> Message
	0, // 1: SampleApplication.DoUnaryStream:input_type -> Message
	0, // 2: SampleApplication.DoStreamUnary:input_type -> Message
	0, // 3: SampleApplication.DoStreamStream:input_type -> Message
	0, // 4: SampleApplication.DoUnaryUnary:output_type -> Message
	0, // 5: SampleApplication.DoUnaryStream:output_type -> Message
	0, // 6: SampleApplication.DoStreamUnary:output_type -> Message
	0, // 7: SampleApplication.DoStreamStream:output_type -> Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sampleapp_proto_init() }
func file_sampleapp_proto_init() {
	if File_sampleapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sampleapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sampleapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sampleapp_proto_goTypes,
		DependencyIndexes: file_sampleapp_proto_depIdxs,
		MessageInfos:      file_sampleapp_proto_msgTypes,
	}.Build()
	File_sampleapp_proto = out.File
	file_sampleapp_proto_rawDesc = nil
	file_sampleapp_proto_goTypes = nil
	file_sampleapp_proto_depIdxs = nil
}
